export interface Product {
  id: string;
  name: string;
  vendor: string;
  category: string;
  price: number;
  description: string;
  rating: number;
  image: string;
  reviews: string[];
  discount?: string;
  stock: string;
  originalPrice?: number;
}

export const marketplaceProducts: Product[] = [
  // Maternal Care (12 items)
  {
    id: "mat-1",
    name: "Pregnacare Plus Dual Pack",
    vendor: "Lekki Central Pharmacy",
    category: "Maternal Care",
    price: 3500,
    originalPrice: 4200,
    description: "Essential prenatal vitamins and minerals plus high purity Omega-3 capsules for pregnant and lactating mothers.",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80",
    reviews: ["Excellent prenatal vitamin!", "Very gentle on the stomach."],
    discount: "16% OFF",
    stock: "In Stock"
  },
  {
    id: "mat-2",
    name: "Premium Adjustable Maternity Belt",
    vendor: "Moms & Kids Care",
    category: "Maternal Care",
    price: 8500,
    description: "Support band designed to reduce lower back and pelvic pain during pregnancy by distributing pressure evenly.",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1590156221122-c413d96c248b?w=400&q=80",
    reviews: ["Really helped my lower back.", "Highly adjustable."],
    stock: "In Stock"
  },
  {
    id: "mat-3",
    name: "Organic Stretch Mark Prevention Oil",
    vendor: "Ahnara Beauty Lab",
    category: "Maternal Care",
    price: 4500,
    originalPrice: 5000,
    description: "Rich blend of sweet almond, rosehip, and jojoba oils to keep belly skin soft and elastic.",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400&q=80",
    reviews: ["Smells amazing!", "Non-greasy stretch mark oil."],
    discount: "10% OFF",
    stock: "In Stock"
  },
  {
    id: "mat-4",
    name: "Comfort Nursing & Maternity Pillow",
    vendor: "Moms & Kids Care",
    category: "Maternal Care",
    price: 12000,
    description: "Ergonomic C-shaped pillow providing support for back, hips, knees, and bump for sleeping or breastfeeding.",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&q=80",
    reviews: ["Incredible support.", "Must-have for sleep comfort."],
    stock: "Only 4 left"
  },
  {
    id: "mat-5",
    name: "Electric Double Breast Pump",
    vendor: "Motherhood Depot",
    category: "Maternal Care",
    price: 24000,
    originalPrice: 28000,
    description: "Ultra-quiet rechargeable breast pump with 9 suction levels and soft silicone massage cushions.",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=400&q=80",
    reviews: ["Silent operation and good battery life.", "Saves so much time."],
    discount: "₦4,000 Deal",
    stock: "In Stock"
  },
  {
    id: "mat-6",
    name: "Disposable Nursing Breast Pads",
    vendor: "Lekki Central Pharmacy",
    category: "Maternal Care",
    price: 1800,
    description: "Ultra-absorbent leak-proof pads with soft dry-touch lining for active nursing mothers.",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80",
    reviews: ["Very absorbent.", "Stays dry all day."],
    stock: "In Stock"
  },
  {
    id: "mat-7",
    name: "Maternity Compression Socks",
    vendor: "Moms & Kids Care",
    category: "Maternal Care",
    price: 3200,
    description: "Graduated compression socks to reduce swelling and fatigue in pregnant women's feet and ankles.",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1582966772680-860e372bb558?w=400&q=80",
    reviews: ["My feet swollen legs felt much lighter."],
    stock: "In Stock"
  },
  {
    id: "mat-8",
    name: "Organic Raspberry Leaf Tea Bags",
    vendor: "Herbals & Healing",
    category: "Maternal Care",
    price: 2100,
    description: "Traditional herbal tea used to tone and strengthen the uterine wall during late pregnancy stages.",
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400&q=80",
    reviews: ["Nice flavor.", "Felt very soothing."],
    stock: "In Stock"
  },
  {
    id: "mat-9",
    name: "Postpartum Recovery Girdle",
    vendor: "Motherhood Depot",
    category: "Maternal Care",
    price: 9500,
    description: "3-in-1 postpartum support wrap to speed up abdominal contraction and waist slimming.",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=400&q=80",
    reviews: ["Excellent compression support.", "Very comfortable postpartum girdle."],
    stock: "In Stock"
  },
  {
    id: "mat-10",
    name: "Soothing Nipple Cream with Lanolin",
    vendor: "Lekki Central Pharmacy",
    category: "Maternal Care",
    price: 2900,
    description: "Hypoallergenic cream to soothe and protect dry, cracked nipples during breastfeeding.",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&q=80",
    reviews: ["Works miracles on sore skin.", "Safe for babies, no need to wash off."],
    stock: "In Stock"
  },
  {
    id: "mat-11",
    name: "Maternity Underwear Cotton Briefs",
    vendor: "Moms & Kids Care",
    category: "Maternal Care",
    price: 4000,
    description: "Over-the-bump breathable organic cotton panties designed for maximum waist comfort.",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=400&q=80",
    reviews: ["Very soft.", "Highly stretchable briefs."],
    stock: "In Stock"
  },
  {
    id: "mat-12",
    name: "Prenatal DHA Softgels",
    vendor: "Victoria Island Drugs",
    category: "Maternal Care",
    price: 6800,
    originalPrice: 7500,
    description: "Doctor-recommended DHA formulation to support fetal brain and vision development.",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&q=80",
    reviews: ["Zero fishy aftertaste.", "High concentration DHA."],
    discount: "Best Deal",
    stock: "In Stock"
  },

  // Pediatrics (12 items)
  {
    id: "ped-1",
    name: "SMA Gold Infant Formula",
    vendor: "Victoria Island Drugs",
    category: "Pediatrics",
    price: 5200,
    originalPrice: 6000,
    description: "Premium baby milk powder formula fortified with iron, Omega 3 & 6, and essential nutrients for child growth.",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&q=80",
    reviews: ["Highly nutritious for my baby.", "Best formula brand."],
    discount: "13% OFF",
    stock: "In Stock"
  },
  {
    id: "ped-2",
    name: "Baby Colic & Gas Relief Drops",
    vendor: "Lekki Central Pharmacy",
    category: "Pediatrics",
    price: 3200,
    description: "Fast-acting simethicone drops to relieve infant gas and colic discomfort safely.",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1550572017-edd951b55104?w=400&q=80",
    reviews: ["Quieted my crying baby within minutes.", "Safe natural formula."],
    stock: "In Stock"
  },
  {
    id: "ped-3",
    name: "Hypoallergenic Organic Baby Wipes",
    vendor: "Toddler Emporium",
    category: "Pediatrics",
    price: 1500,
    description: "Fragrance-free water-based wipes containing organic chamomile extracts for baby's sensitive skin.",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&q=80",
    reviews: ["Super soft wipes.", "No skin rashes ever."],
    stock: "In Stock"
  },
  {
    id: "ped-4",
    name: "Pediatric Multivitamin Drops",
    vendor: "Lekki Central Pharmacy",
    category: "Pediatrics",
    price: 2800,
    description: "Liqui-vit formulation containing Vitamins A, C, D, and Zinc to build toddler immune response.",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=400&q=80",
    reviews: ["Great vitamins.", "Baby loves the flavor."],
    stock: "In Stock"
  },
  {
    id: "ped-5",
    name: "Premium Soft Diapers (Size 3)",
    vendor: "Toddler Emporium",
    category: "Pediatrics",
    price: 7500,
    originalPrice: 8500,
    description: "Ultra-absorbent breathable diapers keeping baby skin dry for up to 12 hours.",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1595079676339-1534801ad6cf?w=400&q=80",
    reviews: ["Leakproof all night long.", "Perfect sizing."],
    discount: "Save ₦1,000",
    stock: "In Stock"
  },
  {
    id: "ped-6",
    name: "Teething Relief Gel",
    vendor: "Lekki Central Pharmacy",
    category: "Pediatrics",
    price: 1900,
    description: "Clove-free, benzocaine-free natural soothing gel to relieve tender toddler gums.",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=400&q=80",
    reviews: ["Instant calming effect."],
    stock: "In Stock"
  },
  {
    id: "ped-7",
    name: "Infant Nasal Aspirator",
    vendor: "Victoria Island Drugs",
    category: "Pediatrics",
    price: 3800,
    description: "Doctor-designed hygienic nasal aspirator to clear baby's blocked nose safely.",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80",
    reviews: ["Easy to clean.", "Crucial for flu season."],
    stock: "In Stock"
  },
  {
    id: "ped-8",
    name: "Digital Infrared Ear Thermometer",
    vendor: "MedTech Equipment",
    category: "Pediatrics",
    price: 14500,
    description: "Fast 1-second accurate temperature readout with color-coded fever indicators.",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1603398938378-e54eab446ddd?w=400&q=80",
    reviews: ["Extremely accurate.", "Very easy to read at night."],
    stock: "Only 2 left"
  },
  {
    id: "ped-9",
    name: "Soothing Toddler Bubble Bath",
    vendor: "Toddler Emporium",
    category: "Pediatrics",
    price: 2400,
    description: "Tear-free calming lavender-infused bubble bath to settle baby before sleep.",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400&q=80",
    reviews: ["Fabulous bubbles.", "Lovely smell."],
    stock: "In Stock"
  },
  {
    id: "ped-10",
    name: "Organic Baby Rice Porridge Cereal",
    vendor: "Toddler Emporium",
    category: "Pediatrics",
    price: 1800,
    description: "Gluten-free organic single grain rice cereal perfect for baby's first solid feeds.",
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&q=80",
    reviews: ["My baby eats it up easily.", "Perfect starting food."],
    stock: "In Stock"
  },
  {
    id: "ped-11",
    name: "Baby Saline Nasal Spray",
    vendor: "Lekki Central Pharmacy",
    category: "Pediatrics",
    price: 1500,
    description: "Gentle saline mist to loosen mucus and clear baby's stuffy nose naturally.",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1550572017-edd951b55104?w=400&q=80",
    reviews: ["No burning, baby is fine with it."],
    stock: "In Stock"
  },
  {
    id: "ped-12",
    name: "Pediatric Hydration Electrolyte Solution",
    vendor: "Lekki Central Pharmacy",
    category: "Pediatrics",
    price: 1200,
    description: "Zinc-fortified oral rehydration fluid to prevent toddler dehydration during illnesses.",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&q=80",
    reviews: ["Effective rehydration.", "Pleasant flavor."],
    stock: "In Stock"
  },

  // Geriatrics (12 items)
  {
    id: "ger-1",
    name: "Deluxe Lightweight Wheelchair",
    vendor: "Geriatric Mobility Supply",
    category: "Geriatrics",
    price: 45000,
    originalPrice: 48000,
    description: "Ergonomically designed steel frame wheelchair with padded armrests, swing-away footrests, and heavy-duty tires.",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1598156690774-c598d9a5330e?w=400&q=80",
    reviews: ["Very durable and comfortable.", "Easy to fold."],
    discount: "6% OFF",
    stock: "In Stock"
  },
  {
    id: "ger-2",
    name: "Adjustable Height Walker with Wheels",
    vendor: "Geriatric Mobility Supply",
    category: "Geriatrics",
    price: 18500,
    description: "Anodized aluminum folding walker featuring 5-inch wheels and comfortable contour hand grips.",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1579684389782-64d84b5e905d?w=400&q=80",
    reviews: ["Sturdy frame.", "Folds flat easily."],
    stock: "In Stock"
  },
  {
    id: "ger-3",
    name: "Premium Adult Incontinence Pads",
    vendor: "Sanitary Products Ltd",
    category: "Geriatrics",
    price: 6200,
    originalPrice: 7000,
    description: "Maximum absorbency pull-up briefs with odor control lining for active seniors.",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&q=80",
    reviews: ["Stays dry, no leakages."],
    discount: "Hot Deal",
    stock: "In Stock"
  },
  {
    id: "ger-4",
    name: "Automatic Upper Arm BP Monitor",
    vendor: "MedTech Equipment",
    category: "Geriatrics",
    price: 18000,
    description: "One-touch operation blood pressure monitor with heart rate detector and large LED display.",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1603398938378-e54eab446ddd?w=400&q=80",
    reviews: ["Doctor-validated readings.", "BP readings are fast and clear."],
    stock: "In Stock"
  },
  {
    id: "ger-5",
    name: "Orthopedic Memory Foam Seat Cushion",
    vendor: "Geriatric Mobility Supply",
    category: "Geriatrics",
    price: 7800,
    description: "U-shaped cushion designed to relieve pressure on tailbone and promote posture for seniors.",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&q=80",
    reviews: ["Saves my back during long sitting sessions."],
    stock: "In Stock"
  },
  {
    id: "ger-6",
    name: "Foldable Walking Cane with LED Light",
    vendor: "Geriatric Mobility Supply",
    category: "Geriatrics",
    price: 4900,
    description: "Collapsible pivoting cane with built-in LED headlamp for safe navigation in dark rooms.",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1582966772680-860e372bb558?w=400&q=80",
    reviews: ["LED light is handy.", "Folds up nicely in bag."],
    stock: "In Stock"
  },
  {
    id: "ger-7",
    name: "Seniors Pill Organizer Box (Weekly)",
    vendor: "Sanitary Products Ltd",
    category: "Geriatrics",
    price: 2200,
    description: "AM/PM compartmentalized weekly pill box with easy push buttons for arthritis sufferers.",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80",
    reviews: ["Buttons pop open easily.", "Great sizing for large pills."],
    stock: "In Stock"
  },
  {
    id: "ger-8",
    name: "Anti-Slip Shower Bath Bench",
    vendor: "Geriatric Mobility Supply",
    category: "Geriatrics",
    price: 15500,
    description: "Heavy-duty aluminum shower seat with non-slip rubber tips and drainage holes.",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80",
    reviews: ["Highly secure chair.", "No assembly tools required."],
    stock: "In Stock"
  },
  {
    id: "ger-9",
    name: "Glucosamine & Chondroitin Joint Gels",
    vendor: "Victoria Island Drugs",
    category: "Geriatrics",
    price: 8900,
    description: "Premium joint supplement designed to support senior knee cartilage and flexibility.",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&q=80",
    reviews: ["Reduced my morning stiffness."],
    stock: "In Stock"
  },
  {
    id: "ger-10",
    name: "Senior In-Home Safety Grab Bar",
    vendor: "Geriatric Mobility Supply",
    category: "Geriatrics",
    price: 5500,
    description: "Rustproof stainless steel grab bar to prevent bathroom slips.",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=400&q=80",
    reviews: ["Strong wall mount."],
    stock: "In Stock"
  },
  {
    id: "ger-11",
    name: "High Strength Omega 3 Fish Oil",
    vendor: "Victoria Island Drugs",
    category: "Geriatrics",
    price: 6200,
    description: "Supports healthy heart functioning and cognitive wellness in elderly users.",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&q=80",
    reviews: ["Excellent fish oil formulation."],
    stock: "In Stock"
  },
  {
    id: "ger-12",
    name: "Geriatric Reaching Aid Grabber",
    vendor: "Geriatric Mobility Supply",
    category: "Geriatrics",
    price: 3900,
    description: "32-inch lightweight grabber tool to pick up keys, jars, or clothes without bending.",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=400&q=80",
    reviews: ["Good grip reach."],
    stock: "In Stock"
  },

  // Diagnostic Scans (12 items)
  {
    id: "dx-1",
    name: "Full Blood Count Diagnostics",
    vendor: "Ahnara Pathlabs",
    category: "Diagnostic Scans",
    price: 8500,
    originalPrice: 9500,
    description: "Comprehensive blood diagnostics covering red blood cells, white blood cells, hemoglobin, hematocrit, and platelet counts.",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1579154204601-01588f351167?w=400&q=80",
    reviews: ["Quick results delivery.", "Super clean collection center."],
    discount: "10% OFF",
    stock: "In Stock"
  },
  {
    id: "dx-2",
    name: "Obstetrics Ultrasound Scan",
    vendor: "Lagos Diagnostic Imaging",
    category: "Diagnostic Scans",
    price: 7500,
    description: "Clinical diagnostic scan showing prenatal growth metrics and fetal heartbeat.",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1516549655169-df83a0774514?w=400&q=80",
    reviews: ["Clear scan copy.", "Doctor explained everything."],
    stock: "In Stock"
  },
  {
    id: "dx-3",
    name: "HbA1c Blood Sugar Screening",
    vendor: "Ahnara Pathlabs",
    category: "Diagnostic Scans",
    price: 5000,
    description: "Evaluates 3-month average glucose levels to monitor prediabetes and diabetes controls.",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400&q=80",
    reviews: ["Fast results."],
    stock: "In Stock"
  },
  {
    id: "dx-4",
    name: "Malaria Parasite (MP) Slide Test",
    vendor: "Ahnara Pathlabs",
    category: "Diagnostic Scans",
    price: 1800,
    description: "Blood microscopy validation to count active malaria parasites for clinical diagnosis.",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1579154204601-01588f351167?w=400&q=80",
    reviews: ["Accurate malaria test."],
    stock: "In Stock"
  },
  {
    id: "dx-5",
    name: "Cardiogram (ECG) Heart Rota Scan",
    vendor: "Lagos Diagnostic Imaging",
    category: "Diagnostic Scans",
    price: 12500,
    originalPrice: 15000,
    description: "12-lead electrocardiogram test monitoring heart rhythm abnormalities.",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1603398938378-e54eab446ddd?w=400&q=80",
    reviews: ["Excellent technician care."],
    discount: "Save ₦2,500",
    stock: "In Stock"
  },
  {
    id: "dx-6",
    name: "Lipid Profile Panel Test",
    vendor: "Ahnara Pathlabs",
    category: "Diagnostic Scans",
    price: 6000,
    description: "Full cholesterol diagnostics checking HDL, LDL, VLDL, and Triglyceride balances.",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400&q=80",
    reviews: ["Detailed profile report."],
    stock: "In Stock"
  },
  {
    id: "dx-7",
    name: "Thyroid Profile (T3, T4, TSH)",
    vendor: "Ahnara Pathlabs",
    category: "Diagnostic Scans",
    price: 11000,
    description: "Hormone blood diagnostics assessing hyperthyroidism and hypothyroidism functions.",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1579154204601-01588f351167?w=400&q=80",
    reviews: ["Delivered in 24 hours."],
    stock: "In Stock"
  },
  {
    id: "dx-8",
    name: "Urinalysis Complete Lab Test",
    vendor: "Ahnara Pathlabs",
    category: "Diagnostic Scans",
    price: 2500,
    description: "Chemical and microscopic analysis of urine parameters to detect UTI and kidney flags.",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400&q=80",
    reviews: ["No-stress test process."],
    stock: "In Stock"
  },
  {
    id: "dx-9",
    name: "Serum Creatinine Kidney Scan",
    vendor: "Ahnara Pathlabs",
    category: "Diagnostic Scans",
    price: 3200,
    description: "Assesses blood filtration rates to evaluate overall kidney function.",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1516549655169-df83a0774514?w=400&q=80",
    reviews: ["Clear indicator levels."],
    stock: "In Stock"
  },
  {
    id: "dx-10",
    name: "Liver Function Test (LFT) Panel",
    vendor: "Ahnara Pathlabs",
    category: "Diagnostic Scans",
    price: 8900,
    description: "Fractions analysis of bilirubin, AST, ALT, and alkaline phosphatase enzymes.",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1579154204601-01588f351167?w=400&q=80",
    reviews: ["Fast LFT panel diagnostics."],
    stock: "In Stock"
  },
  {
    id: "dx-11",
    name: "Prostate Specific Antigen (PSA) Test",
    vendor: "Ahnara Pathlabs",
    category: "Diagnostic Scans",
    price: 7500,
    description: "Blood diagnostic scan monitoring prostate health markers in seniors.",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400&q=80",
    reviews: ["Accurate PSA test."],
    stock: "In Stock"
  },
  {
    id: "dx-12",
    name: "Hepatitis B Surface Antigen Test",
    vendor: "Ahnara Pathlabs",
    category: "Diagnostic Scans",
    price: 2200,
    description: "Rapid blood diagnostics to detect active HBV infections.",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1579154204601-01588f351167?w=400&q=80",
    reviews: ["Results received in 2 hours via SMS."],
    stock: "In Stock"
  },

  // Medical Supplies (12 items)
  {
    id: "sup-1",
    name: "Oxygen Concentrator (5L/min)",
    vendor: "Ahnara MedSupplies",
    category: "Medical Supplies",
    price: 95000,
    originalPrice: 110000,
    description: "Continuous flow medical-grade oxygen generator with nebulizer port and warning sensor alarms.",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80",
    reviews: ["Life-saver for chronic conditions.", "Quiet operation."],
    discount: "13% OFF",
    stock: "Only 3 left"
  },
  {
    id: "sup-2",
    name: "3-Ply Surgical Face Masks (Box of 50)",
    vendor: "Ahnara MedSupplies",
    category: "Medical Supplies",
    price: 1800,
    description: "High-filtration earloop face masks with fluid resistance layers.",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80",
    reviews: ["Very breathable.", "Comfortable elastic earloops."],
    stock: "In Stock"
  },
  {
    id: "sup-3",
    name: "Nitrile Examination Gloves (Box of 100)",
    vendor: "Ahnara MedSupplies",
    category: "Medical Supplies",
    price: 4500,
    description: "Powder-free, latex-free exam gloves with textured fingertips for medical use.",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80",
    reviews: ["High tear resistance.", "Perfect stretch fitting."],
    stock: "In Stock"
  },
  {
    id: "sup-4",
    name: "Hand & Surface Sanitizer (5L)",
    vendor: "Ahnara MedSupplies",
    category: "Medical Supplies",
    price: 8000,
    description: "75% Isopropyl alcohol antiseptic gel for instant disinfection.",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80",
    reviews: ["Non-drying formula."],
    stock: "In Stock"
  },
  {
    id: "sup-5",
    name: "Digital Pulse Oximeter",
    vendor: "MedTech Equipment",
    category: "Medical Supplies",
    price: 6500,
    description: "Monitors oxygen saturation levels (SpO2) and heart pulse rate instantly.",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1603398938378-e54eab446ddd?w=400&q=80",
    reviews: ["Very fast reading.", "Clear LED screen."],
    stock: "In Stock"
  },
  {
    id: "sup-6",
    name: "Infrared Forehead Thermometer",
    vendor: "MedTech Equipment",
    category: "Medical Supplies",
    price: 9800,
    description: "Non-contact thermometer checking temperature from 2 inches away for sanitary control.",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1603398938378-e54eab446ddd?w=400&q=80",
    reviews: ["Perfect for home checks."],
    stock: "In Stock"
  },
  {
    id: "sup-7",
    name: "Disposable Syringes with Needle (Box of 100)",
    vendor: "Ahnara MedSupplies",
    category: "Medical Supplies",
    price: 5200,
    description: "Sterile, pyrogen-free 5ml syringes with ultra-sharp luer lock needles.",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80",
    reviews: ["Zero complaints, completely sterile."],
    stock: "In Stock"
  },
  {
    id: "sup-8",
    name: "Surgical Spirit (70% Ethanol 500ml)",
    vendor: "Lekki Central Pharmacy",
    category: "Medical Supplies",
    price: 1100,
    description: "Astringent and antiseptic liquid for skin prep prior to injection draws.",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80",
    reviews: ["Standard antiseptic spirit."],
    stock: "In Stock"
  },
  {
    id: "sup-9",
    name: "Nebulizer Therapy Machine",
    vendor: "MedTech Equipment",
    category: "Medical Supplies",
    price: 19500,
    description: "Heavy-duty compressor nebulizer designed to deliver medication mist for respiratory relief.",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1603398938378-e54eab446ddd?w=400&q=80",
    reviews: ["Strong consistent mist flow.", "Comes with adult and child masks."],
    stock: "In Stock"
  },
  {
    id: "sup-10",
    name: "Surgical Cotton Wool (500g Roll)",
    vendor: "Ahnara MedSupplies",
    category: "Medical Supplies",
    price: 1500,
    description: "100% pure absorbent cotton roll for medical wound dressings.",
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80",
    reviews: ["Very soft.", "Highly absorbent."],
    stock: "In Stock"
  },
  {
    id: "sup-11",
    name: "Adhesive Wound Dressing Plasters (Box of 100)",
    vendor: "Ahnara MedSupplies",
    category: "Medical Supplies",
    price: 2000,
    description: "Breathable flexible band-aids to protect minor scratches and cuts.",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80",
    reviews: ["Good adhesive grip."],
    stock: "In Stock"
  },
  {
    id: "sup-12",
    name: "First Aid Kit (Clinical Standard)",
    vendor: "Ahnara MedSupplies",
    category: "Medical Supplies",
    price: 12500,
    description: "Equipped wall-mountable emergency first aid kit with scissors, burn dressings, and bandages.",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80",
    reviews: ["Very comprehensive for offices and home safety."],
    stock: "In Stock"
  }
];
